package org.cytoscape.tiedie.internal;

public class TieDieHelp extends javax.swing.JFrame {

    private String helpString;

    /**
     * Creates new form TieDieHelp
     */
    public TieDieHelp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().addContainerGap().add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().addContainerGap().add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE).addContainerGap()));
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TieDieHelp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public void setText(int buttonNumber) {
      
        helpString =
                "TieDIE: \n\n"
                + "The TieDIE algorithm computes a subnetwork of gene and protein \n"
                + "interactions that connect genomic perturbations to \n"
                + "gene expression changes characteristic of cancer subtypes.\n"
                + "The pathways derived in this way predict interlinking genes"
                + "that may correspond to essential components of cancer signaling & \n"
                + "may provide a mechanistic explanation of tumor behavior \n" 
                + "and suggest subtype-specific drug targets.\n"     
                + "----\n"
                + "Importing inputs for the TieDIE algorithm ::::::: \n"
                + "Import network using File -> import -> Network -> file \n"
                + "Import table files using File -> import -> Table -> file \n"
                + "----\n"
                + "----\n"
                + "Running TieDIE app :::::: \n"
                + "Click on Apps menu \n"
                + "Click on TieDIE which opens a tabbed panel in control panel \n"
                + "Select the columns for diffusion using comboboxes \n"
                + "Select the way of diffusion using radiobuttons \n"
                + "Click on run TieDIE algorithm \n"
                + "----\n"
                + "Find the new subnetwork created programmatically \n"
                + "and the corresponding changes in the input network \n\n" ;
        
                

        this.setTitle("TieDIE Help : ");
        
        jTextArea1.setText(helpString);
        jTextArea1.setCaretPosition(0);
    }
}
